title: UEFI Playground
description: Learning UEFI Development

remote_theme: just-the-docs/just-the-docs

color_scheme: dark

search_enabled: true

markdown: kramdown

aux_links:
  GitHub: https://github.com/koenigr/uefi-playground

sass:
  style: compressed

plugins:
  .jekyll-remote-theme